name: Run Example RN CI Test

on:
  push:
    branches:
      - main

env:
  ADB_INSTALL_TIMEOUT: 30
  ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60

jobs:

  test:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      # - name: APK Build Cache
      #   uses: actions/cache@v3
      #   id: build-cache
      #   with:
      #     path: |
      #       ./android/app/build
      #     key: ${{ runner.os }}-apk-${{ hashFiles('./src') }}
      
      - name: AVD Emulator Cache
        uses: actions/cache@v3
        id: emulator-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb
          key: ${{ runner.os }}-avd

      - name: Install Node Dependencies
        run: yarn install --immutable

      # - name: Build Android APK
      #   if: steps.build-cache.outputs.cache-hit != 'true'
      #   run: yarn build

      - name: create AVD and generate snapshot for caching
        if: steps.emulator-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          avd-name: Pixel_3a_API_30
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run React Native tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          avd-name: Pixel_3a_API_30
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            yarn adb:install
            yarn adb:reverse
            yarn test